/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/kyc`; params?: Router.UnknownInputParams; } | { pathname: `/profiling`; params?: Router.UnknownInputParams; } | { pathname: `/referral`; params?: Router.UnknownInputParams; } | { pathname: `/select-persona`; params?: Router.UnknownInputParams; } | { pathname: `/sign-in`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/knowledge` | `/knowledge`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/marketplace` | `/marketplace`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/portfolio` | `/portfolio`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/invest/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/property/[slug]`, params: Router.UnknownInputParams & { slug: string | number; } } | { pathname: `/ref/[code]`, params: Router.UnknownInputParams & { code: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/kyc`; params?: Router.UnknownOutputParams; } | { pathname: `/profiling`; params?: Router.UnknownOutputParams; } | { pathname: `/referral`; params?: Router.UnknownOutputParams; } | { pathname: `/select-persona`; params?: Router.UnknownOutputParams; } | { pathname: `/sign-in`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/knowledge` | `/knowledge`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/marketplace` | `/marketplace`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/portfolio` | `/portfolio`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `/invest/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/property/[slug]`, params: Router.UnknownOutputParams & { slug: string; } } | { pathname: `/ref/[code]`, params: Router.UnknownOutputParams & { code: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/kyc${`?${string}` | `#${string}` | ''}` | `/profiling${`?${string}` | `#${string}` | ''}` | `/referral${`?${string}` | `#${string}` | ''}` | `/select-persona${`?${string}` | `#${string}` | ''}` | `/sign-in${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/knowledge${`?${string}` | `#${string}` | ''}` | `/knowledge${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/marketplace${`?${string}` | `#${string}` | ''}` | `/marketplace${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/portfolio${`?${string}` | `#${string}` | ''}` | `/portfolio${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/kyc`; params?: Router.UnknownInputParams; } | { pathname: `/profiling`; params?: Router.UnknownInputParams; } | { pathname: `/referral`; params?: Router.UnknownInputParams; } | { pathname: `/select-persona`; params?: Router.UnknownInputParams; } | { pathname: `/sign-in`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/knowledge` | `/knowledge`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/marketplace` | `/marketplace`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/portfolio` | `/portfolio`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | `/invest/${Router.SingleRoutePart<T>}` | `/property/${Router.SingleRoutePart<T>}` | `/ref/${Router.SingleRoutePart<T>}` | { pathname: `/invest/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/property/[slug]`, params: Router.UnknownInputParams & { slug: string | number; } } | { pathname: `/ref/[code]`, params: Router.UnknownInputParams & { code: string | number; } };
    }
  }
}
