// ============================================================================
// WealthSpot Shared Types – Barrel Export
// ============================================================================

// Enums
export {
  UserRole,
  KycStatus,
  AssetType,
  PropertyStatus,
  InvestmentStatus,
  TransactionType,
  PostType,
  LoanStatus,
  KycDocumentType,
  DocumentVerificationStatus,
  ApprovalCategory,
  ApprovalStatus,
  ApprovalPriority,
  VaultType,
  OpportunityStatus,
  CommunitySubtype,
  PersonaType,
  FeatureKey,
  InviteStatus,
} from "./enums";

// Entity models
export type {
  User,
  UserCreate,
  UserUpdate,
  UserProfile,
  KycDocument,
  KycSubmission,
  Builder,
  BuilderCreate,
  Property,
  PropertyListItem,
  PropertyDetail,
  PropertyCreate,
  PropertyUpdate,
  PropertyFilters,
  Investment,
  InvestmentCreate,
  InvestmentRead,
  ConfirmPayment,
  InvestmentSummary,
  Transaction,
  PortfolioSummary,
  CommunityPost,
  CommunityPostCreate,
  CommunityReply,
  CommunityReplyCreate,
  Referral,
  AuditLog,
  Loan,
  LoanCreate,
  ApprovalRequest,
  ApprovalCreate,
  ApprovalReview,
  ApprovalStats,
  Opportunity,
  OpportunityCreate,
  PlatformConfig,
  PlatformConfigCreate,
  PlatformConfigUpdate,
  ControlCentreDashboard,
  VaultProfileQuestion,
  QuestionOption,
  SliderOptions,
  UserProfileAnswer,
  UserProfileAnswerCreate,
  UserProfileAnswerBulk,
  OpportunityCustomQuestion,
  OpportunityCustomQuestionCreate,
  PersonalityDimension,
  MatchScore,
  MatchBreakdown,
  MatchedUser,
  ProfilingProgress,
  PersonaSelectionRequest,
  VaultFeatureFlag,
  VaultFeatureFlagUpdate,
  VaultFeatureMatrixUpdate,
  MyFeatureFlags,
  AdminInvite,
  AdminInviteCreate,
} from "./models";

// API response types
export type {
  ApiResponse,
  ApiError,
  PaginatedResponse,
  TokenPair,
  RazorpayWebhookEvent,
  PresignedUploadUrl,
  AdminDashboardStats,
  LenderDashboardStats,
} from "./api";

// WealthSpot Shield — 7-layer trust framework
export {
  AssessmentStatus,
  ASSESSMENT_CATEGORIES,
  countAssessmentSlots,
  findCategory,
  findSubItem,
} from "./assessments";
export type {
  AssessmentCategoryCode,
  AssessmentOverallStatus,
  PerformedBy,
  AssessmentInputType,
  AssessmentSubItem,
  AssessmentCategory,
  AssessmentSubItemRead,
  AssessmentDocumentRead,
  AssessmentCategoryRead,
  AssessmentSummaryRead,
  OpportunityRiskFlagRead,
  ShieldMetrics,
} from "./assessments";
