"""project roadmap and thesis fields

Revision ID: 071_project_roadmap_thesis
Revises: 070_opportunity_extra_fields
Create Date: 2026-06-04 11:27:00.000000

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "071_project_roadmap_thesis"
down_revision: Union[str, None] = (
    "43619bfcc037"  # Ensure this matches the actual previous revision if needed.
)
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "opportunities",
        sa.Column("project_roadmap", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column("opportunities", sa.Column("risk_factors", sa.Text(), nullable=True))
    op.add_column("opportunities", sa.Column("why_investors", sa.Text(), nullable=True))
    op.add_column("opportunities", sa.Column("investment_thesis", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("opportunities", "investment_thesis")
    op.drop_column("opportunities", "why_investors")
    op.drop_column("opportunities", "risk_factors")
    op.drop_column("opportunities", "project_roadmap")
    # ### end Alembic commands ###
