"""Add opportunity and vault explorer columns

Revision ID: 2c5529d18a28
Revises: c4beb3970272
Create Date: 2026-05-27 09:08:48.308158

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2c5529d18a28"
down_revision: Union[str, None] = "c4beb3970272"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("opportunities", sa.Column("usps", postgresql.ARRAY(sa.Text()), nullable=True))
    op.create_unique_constraint(
        "uq_vault_explorer_user_vault", "vault_explorers", ["user_id", "vault_type"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_vault_explorer_user_vault", "vault_explorers", type_="unique")
    op.drop_column("opportunities", "usps")
    # ### end Alembic commands ###
