"""add consent_logs table

Revision ID: 6471f537b4b0
Revises: 066_remove_community_forum
Create Date: 2026-05-24 19:43:18.926347

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6471f537b4b0"
down_revision: Union[str, None] = "066_remove_community_forum"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "consent_logs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("consent_type", sa.String(length=50), nullable=False),
        sa.Column("consented", sa.Boolean(), nullable=False),
        sa.Column("target_id", sa.String(length=100), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("user_agent", sa.String(length=255), nullable=True),
        sa.Column("location", sa.String(length=255), nullable=True),
        sa.Column("device_details", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_consent_logs_consent_type"),
        "consent_logs",
        ["consent_type"],
        unique=False,
        if_not_exists=True,
    )
    op.create_index(
        op.f("ix_consent_logs_target_id"),
        "consent_logs",
        ["target_id"],
        unique=False,
        if_not_exists=True,
    )
    op.drop_index(op.f("idx_admin_invites_email"), if_exists=True, table_name="admin_invites")
    op.drop_index(op.f("idx_admin_invites_token"), if_exists=True, table_name="admin_invites")
    op.create_table_comment(
        "admin_invites",
        "Invite tokens for admin/super_admin role onboarding",
        existing_comment=None,
        schema=None,
    )
    op.alter_column(
        "app_images",
        "is_active",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("true"),
    )
    op.alter_column(
        "app_images",
        "sort_order",
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "app_images",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "app_images",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(
        op.f("idx_app_images_active"),
        table_name="app_images",
        postgresql_where="(is_active = true)",
    )
    op.drop_index(op.f("idx_app_images_page"), if_exists=True, table_name="app_images")
    op.drop_index(op.f("idx_app_images_page_section"), if_exists=True, table_name="app_images")
    op.drop_constraint(op.f("uq_app_image_page_section"), "app_images", type_="unique")
    op.alter_column(
        "app_videos",
        "is_active",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("true"),
    )
    op.alter_column(
        "app_videos",
        "sort_order",
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "app_videos",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "app_videos",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(
        op.f("idx_app_videos_active"),
        table_name="app_videos",
        postgresql_where="(is_active = true)",
    )
    op.drop_index(op.f("idx_app_videos_page"), if_exists=True, table_name="app_videos")
    op.drop_index(op.f("idx_app_videos_page_section"), if_exists=True, table_name="app_videos")
    op.drop_index(op.f("ix_app_videos_uploaded_by"), if_exists=True, table_name="app_videos")
    op.drop_constraint(op.f("uq_app_video_page_section"), "app_videos", type_="unique")
    op.alter_column(
        "approval_requests",
        "auto_approve",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "approval_requests",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "approval_requests",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(
        op.f("idx_approval_requests_category"), if_exists=True, table_name="approval_requests"
    )
    op.drop_index(
        op.f("idx_approval_requests_category_status"),
        if_exists=True,
        table_name="approval_requests",
    )
    op.drop_index(
        op.f("idx_approval_requests_created_at"), if_exists=True, table_name="approval_requests"
    )
    op.drop_index(
        op.f("idx_approval_requests_requester"), if_exists=True, table_name="approval_requests"
    )
    op.drop_index(
        op.f("idx_approval_requests_reviewer"), if_exists=True, table_name="approval_requests"
    )
    op.drop_index(
        op.f("idx_approval_requests_status"), if_exists=True, table_name="approval_requests"
    )
    op.create_index(
        op.f("ix_approval_requests_category"),
        "approval_requests",
        ["category"],
        unique=False,
        if_not_exists=True,
    )
    op.create_index(
        op.f("ix_approval_requests_created_at"),
        "approval_requests",
        ["created_at"],
        unique=False,
        if_not_exists=True,
    )
    op.create_index(
        op.f("ix_approval_requests_reviewer_id"),
        "approval_requests",
        ["reviewer_id"],
        unique=False,
        if_not_exists=True,
    )
    op.create_index(
        op.f("ix_approval_requests_status"),
        "approval_requests",
        ["status"],
        unique=False,
        if_not_exists=True,
    )
    op.drop_table_comment(
        "approval_requests",
        existing_comment="Generic approval workflow for all platform actions",
        schema=None,
    )
    op.alter_column(
        "audit_logs",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(
        op.f("idx_audit_logs_actor"),
        table_name="audit_logs",
        postgresql_where="(actor_id IS NOT NULL)",
    )
    op.drop_index(op.f("idx_audit_logs_created_at"), if_exists=True, table_name="audit_logs")
    op.drop_index(
        op.f("idx_audit_logs_created_brin"), table_name="audit_logs", postgresql_using="brin"
    )
    op.drop_index(op.f("idx_audit_logs_resource"), if_exists=True, table_name="audit_logs")
    op.drop_index(op.f("idx_bank_details_user_id"), if_exists=True, table_name="bank_details")
    op.create_index(
        op.f("ix_bank_details_user_id"),
        "bank_details",
        ["user_id"],
        unique=False,
        if_not_exists=True,
    )
    op.create_table_comment(
        "bank_details",
        "Bank details with encrypted sensitive fields",
        existing_comment=None,
        schema=None,
    )
    op.alter_column(
        "builder_questions",
        "is_required",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("true"),
    )
    op.alter_column(
        "builder_questions",
        "sort_order",
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "builder_questions",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "builder_questions",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(
        op.f("ix_builder_updates_creator_id"), if_exists=True, table_name="builder_updates"
    )
    op.alter_column(
        "builders",
        "verified",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "builders",
        "projects_completed",
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "builders",
        "total_sqft_delivered",
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "builders",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_constraint(op.f("builders_user_id_fkey"), "builders", type_="foreignkey")
    op.create_foreign_key(None, "builders", "users", ["user_id"], ["id"])
    op.drop_column("builders", "rera_number")
    op.alter_column(
        "companies",
        "country",
        existing_type=sa.VARCHAR(length=100),
        nullable=False,
        existing_server_default=sa.text("'India'::character varying"),
    )
    op.alter_column(
        "companies",
        "projects_completed",
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "companies",
        "verified",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "companies",
        "verification_status",
        existing_type=sa.VARCHAR(length=20),
        nullable=False,
        existing_server_default=sa.text("'pending'::character varying"),
    )
    op.alter_column(
        "companies",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "companies",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(
        op.f("idx_companies_cin"),
        table_name="companies",
        postgresql_where="(cin IS NOT NULL, if_exists=True)",
    )
    op.drop_index(op.f("idx_companies_name"), if_exists=True, table_name="companies")
    op.drop_index(op.f("idx_companies_user"), if_exists=True, table_name="companies")
    op.drop_index(op.f("idx_companies_user_id"), if_exists=True, table_name="companies")
    op.drop_index(op.f("idx_companies_verified"), if_exists=True, table_name="companies")
    op.drop_index(op.f("ix_companies_approval_id"), if_exists=True, table_name="companies")
    op.create_index(
        op.f("ix_companies_user_id"), "companies", ["user_id"], unique=False, if_not_exists=True
    )
    op.drop_table_comment(
        "companies",
        existing_comment="Builder/developer company profiles for opportunity creation",
        schema=None,
    )
    op.drop_column("companies", "rera_number")
    op.drop_index(
        op.f("ix_eoi_form_options_field_active"), if_exists=True, table_name="eoi_form_options"
    )
    op.alter_column(
        "eoi_question_answers",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(op.f("ix_eoi_qa_eoi_id"), if_exists=True, table_name="eoi_question_answers")
    op.create_index(
        op.f("ix_eoi_question_answers_eoi_id"),
        "eoi_question_answers",
        ["eoi_id"],
        unique=False,
        if_not_exists=True,
    )
    op.drop_index(op.f("idx_eoi_stage_history_eoi"), if_exists=True, table_name="eoi_stage_history")
    op.drop_index(
        op.f("idx_eoi_stage_history_eoi_status"), if_exists=True, table_name="eoi_stage_history"
    )
    op.alter_column(
        "expressions_of_interest",
        "communication_consent",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("true"),
    )
    op.alter_column(
        "expressions_of_interest",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "expressions_of_interest",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(
        op.f("idx_eoi_opportunity_status"), if_exists=True, table_name="expressions_of_interest"
    )
    op.drop_index(op.f("idx_eoi_status"), if_exists=True, table_name="expressions_of_interest")
    op.drop_index(op.f("idx_eoi_status_opid"), if_exists=True, table_name="expressions_of_interest")
    op.drop_index(op.f("idx_eoi_user_id"), if_exists=True, table_name="expressions_of_interest")
    op.drop_index(
        op.f("ix_eoi_opportunity_id"), if_exists=True, table_name="expressions_of_interest"
    )
    op.drop_index(op.f("ix_eoi_status"), if_exists=True, table_name="expressions_of_interest")
    op.drop_index(op.f("ix_eoi_user_id"), if_exists=True, table_name="expressions_of_interest")
    op.create_index(
        op.f("ix_expressions_of_interest_status"),
        "expressions_of_interest",
        ["status"],
        unique=False,
        if_not_exists=True,
    )
    op.drop_index(op.f("idx_group_messages_group_id"), if_exists=True, table_name="group_messages")
    op.create_index(
        op.f("ix_group_messages_group_id"),
        "group_messages",
        ["group_id"],
        unique=False,
        if_not_exists=True,
    )
    op.drop_table_comment(
        "group_messages", existing_comment="Messages sent to role groups", schema=None
    )
    op.alter_column(
        "indian_pincodes",
        "delivery",
        existing_type=sa.VARCHAR(length=10),
        nullable=False,
        existing_server_default=sa.text("'Delivery'::character varying"),
    )
    op.drop_table_comment(
        "indian_pincodes",
        existing_comment="India Post pincode reference for address auto-fill",
        schema=None,
    )
    op.drop_index(
        op.f("ix_investment_txn_records_legacy_inv_id"), table_name="investment_transaction_records"
    )
    op.drop_index(
        op.f("ix_investment_txn_records_opp_inv_id"), table_name="investment_transaction_records"
    )
    op.drop_index(
        op.f("ix_investment_txn_records_user_id"), table_name="investment_transaction_records"
    )
    op.alter_column(
        "investments",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "investments",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(op.f("idx_inv_status_created"), if_exists=True, table_name="investments")
    op.drop_index(
        op.f("idx_investments_razorpay_order_id"), if_exists=True, table_name="investments"
    )
    op.drop_index(op.f("idx_investments_status"), if_exists=True, table_name="investments")
    op.drop_index(op.f("idx_investments_user_status"), if_exists=True, table_name="investments")
    op.drop_constraint(op.f("investments_property_id_fkey"), "investments", type_="foreignkey")
    op.drop_constraint(op.f("investments_user_id_fkey"), "investments", type_="foreignkey")
    op.create_foreign_key(None, "investments", "users", ["user_id"], ["id"])
    op.create_foreign_key(None, "investments", "properties", ["property_id"], ["id"])
    op.alter_column(
        "kyc_documents",
        "verification_status",
        existing_type=sa.VARCHAR(length=20),
        nullable=False,
        existing_server_default=sa.text("'PENDING'::character varying"),
    )
    op.alter_column(
        "kyc_documents",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "loans",
        "amount_repaid",
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "loans",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(op.f("idx_loans_lender"), if_exists=True, table_name="loans")
    op.drop_index(op.f("idx_loans_lender_status"), if_exists=True, table_name="loans")
    op.drop_index(op.f("idx_loans_status"), if_exists=True, table_name="loans")
    op.alter_column(
        "notifications",
        "is_read",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "notifications",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(op.f("idx_notifications_is_read"), if_exists=True, table_name="notifications")
    op.drop_index(
        op.f("idx_notifications_unread"),
        table_name="notifications",
        postgresql_where="(read_at IS NULL)",
    )
    op.drop_index(
        op.f("idx_notifications_user_created"), if_exists=True, table_name="notifications"
    )
    op.drop_index(op.f("idx_notifications_user_id"), if_exists=True, table_name="notifications")
    op.create_index(
        op.f("ix_notifications_created_at"),
        "notifications",
        ["created_at"],
        unique=False,
        if_not_exists=True,
    )
    op.create_index(
        op.f("ix_notifications_user_id"),
        "notifications",
        ["user_id"],
        unique=False,
        if_not_exists=True,
    )
    op.drop_table_comment(
        "notifications", existing_comment="In-app, email, push notification tracking", schema=None
    )
    op.alter_column(
        "opportunities",
        "country",
        existing_type=sa.VARCHAR(length=100),
        nullable=False,
        existing_server_default=sa.text("'India'::character varying"),
    )
    op.alter_column(
        "opportunities",
        "raised_amount",
        existing_type=sa.NUMERIC(precision=15, scale=2),
        nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "opportunities",
        "investor_count",
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "opportunities",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "opportunities",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(op.f("idx_opp_company"), if_exists=True, table_name="opportunities")
    op.drop_index(op.f("idx_opp_vault_status"), if_exists=True, table_name="opportunities")
    op.drop_index(op.f("idx_opportunities_city"), if_exists=True, table_name="opportunities")
    op.drop_index(
        op.f("idx_opportunities_community_subtype"),
        table_name="opportunities",
        postgresql_where="(community_subtype IS NOT NULL)",
    )
    op.drop_index(op.f("idx_opportunities_company"), if_exists=True, table_name="opportunities")
    op.drop_index(op.f("idx_opportunities_creator"), if_exists=True, table_name="opportunities")
    op.drop_index(op.f("idx_opportunities_slug"), if_exists=True, table_name="opportunities")
    op.drop_index(op.f("idx_opportunities_status"), if_exists=True, table_name="opportunities")
    op.drop_index(
        op.f("idx_opportunities_vault_status"), if_exists=True, table_name="opportunities"
    )
    op.drop_index(op.f("idx_opportunities_vault_type"), if_exists=True, table_name="opportunities")
    op.drop_index(op.f("ix_opportunities_approval_id"), if_exists=True, table_name="opportunities")
    op.drop_index(
        op.f("ix_opportunities_investment_mode"), if_exists=True, table_name="opportunities"
    )
    op.drop_constraint(op.f("opportunities_slug_key"), "opportunities", type_="unique")
    op.create_index(
        op.f("ix_opportunities_city"), "opportunities", ["city"], unique=False, if_not_exists=True
    )
    op.create_index(
        op.f("ix_opportunities_slug"), "opportunities", ["slug"], unique=True, if_not_exists=True
    )
    op.create_index(
        op.f("ix_opportunities_status"),
        "opportunities",
        ["status"],
        unique=False,
        if_not_exists=True,
    )
    op.create_index(
        op.f("ix_opportunities_vault_type"),
        "opportunities",
        ["vault_type"],
        unique=False,
        if_not_exists=True,
    )
    op.drop_constraint(op.f("opportunities_company_id_fkey"), "opportunities", type_="foreignkey")
    op.create_foreign_key(None, "opportunities", "companies", ["company_id"], ["id"])
    op.drop_table_comment(
        "opportunities",
        existing_comment="Multi-vault investment opportunities (Wealth / Opportunity / Community)",
        schema=None,
    )
    op.drop_index(
        op.f("idx_oaa_user_opp"), if_exists=True, table_name="opportunity_application_answers"
    )
    op.drop_constraint(
        op.f("uq_opp_application_answer"), "opportunity_application_answers", type_="unique"
    )
    op.create_index(
        op.f("ix_opportunity_application_answers_user_id"),
        "opportunity_application_answers",
        ["user_id"],
        unique=False,
        if_not_exists=True,
    )
    op.drop_index(op.f("ix_oa_category"), if_exists=True, table_name="opportunity_assessments")
    op.drop_index(op.f("ix_oa_opportunity"), if_exists=True, table_name="opportunity_assessments")
    op.drop_index(op.f("ix_oa_status"), if_exists=True, table_name="opportunity_assessments")
    op.create_index(
        op.f("ix_opportunity_assessments_category_code"),
        "opportunity_assessments",
        ["category_code"],
        unique=False,
        if_not_exists=True,
    )
    op.create_index(
        op.f("ix_opportunity_assessments_opportunity_id"),
        "opportunity_assessments",
        ["opportunity_id"],
        unique=False,
        if_not_exists=True,
    )
    op.create_index(
        op.f("ix_opportunity_assessments_status"),
        "opportunity_assessments",
        ["status"],
        unique=False,
        if_not_exists=True,
    )
    op.alter_column(
        "opportunity_comm_mappings",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(
        op.f("ix_comm_mappings_opportunity_id"),
        if_exists=True,
        table_name="opportunity_comm_mappings",
    )
    op.create_index(
        op.f("ix_opportunity_comm_mappings_opportunity_id"),
        "opportunity_comm_mappings",
        ["opportunity_id"],
        unique=False,
        if_not_exists=True,
    )
    op.drop_index(
        op.f("idx_ocq_opportunity"), if_exists=True, table_name="opportunity_custom_questions"
    )
    op.create_index(
        op.f("ix_opportunity_custom_questions_opportunity_id"),
        "opportunity_custom_questions",
        ["opportunity_id"],
        unique=False,
        if_not_exists=True,
    )
    op.drop_constraint(
        op.f("uq_opportunity_documents_opp_doc_type"), "opportunity_documents", type_="unique"
    )
    op.alter_column(
        "opportunity_form_options",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "opportunity_investments",
        "returns_amount",
        existing_type=sa.NUMERIC(precision=15, scale=2),
        nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "opportunity_investments",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "opportunity_investments",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(
        op.f("idx_opp_inv_status_created"), if_exists=True, table_name="opportunity_investments"
    )
    op.drop_index(
        op.f("idx_opp_investments_opp_status"), if_exists=True, table_name="opportunity_investments"
    )
    op.drop_index(
        op.f("idx_opp_investments_opportunity"),
        if_exists=True,
        table_name="opportunity_investments",
    )
    op.drop_index(
        op.f("idx_opp_investments_status"), if_exists=True, table_name="opportunity_investments"
    )
    op.drop_index(
        op.f("idx_opp_investments_user"), if_exists=True, table_name="opportunity_investments"
    )
    op.create_index(
        op.f("ix_opportunity_investments_opportunity_id"),
        "opportunity_investments",
        ["opportunity_id"],
        unique=False,
        if_not_exists=True,
    )
    op.create_index(
        op.f("ix_opportunity_investments_status"),
        "opportunity_investments",
        ["status"],
        unique=False,
        if_not_exists=True,
    )
    op.create_index(
        op.f("ix_opportunity_investments_user_id"),
        "opportunity_investments",
        ["user_id"],
        unique=False,
        if_not_exists=True,
    )
    op.drop_table_comment(
        "opportunity_investments",
        existing_comment="Links investments to specific opportunities for vault-level aggregation",
        schema=None,
    )
    op.alter_column(
        "opportunity_likes",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(
        op.f("ix_opp_likes_opportunity_id"), if_exists=True, table_name="opportunity_likes"
    )
    op.drop_index(op.f("ix_opp_likes_user_id"), if_exists=True, table_name="opportunity_likes")
    op.create_index(
        op.f("ix_opportunity_likes_opportunity_id"),
        "opportunity_likes",
        ["opportunity_id"],
        unique=False,
        if_not_exists=True,
    )
    op.create_index(
        op.f("ix_opportunity_likes_user_id"),
        "opportunity_likes",
        ["user_id"],
        unique=False,
        if_not_exists=True,
    )
    op.alter_column(
        "opportunity_media",
        "media_type",
        existing_type=sa.VARCHAR(length=20),
        type_=sa.String(length=10),
        existing_nullable=False,
        existing_server_default=sa.text("'image'::character varying"),
    )
    op.alter_column(
        "opportunity_media",
        "filename",
        existing_type=sa.VARCHAR(length=500),
        type_=sa.Text(),
        existing_nullable=True,
    )
    op.alter_column(
        "opportunity_media",
        "sort_order",
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "opportunity_media",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(op.f("idx_opp_media_opp_id"), if_exists=True, table_name="opportunity_media")
    op.drop_index(
        op.f("idx_opp_media_opportunity_id"), if_exists=True, table_name="opportunity_media"
    )
    op.drop_index(op.f("idx_opp_media_type"), if_exists=True, table_name="opportunity_media")
    op.drop_index(op.f("ix_om_assessment"), if_exists=True, table_name="opportunity_media")
    op.create_index(
        op.f("ix_opportunity_media_opportunity_id"),
        "opportunity_media",
        ["opportunity_id"],
        unique=False,
        if_not_exists=True,
    )
    op.drop_index(op.f("ix_orf_opportunity"), if_exists=True, table_name="opportunity_risk_flags")
    op.create_index(
        op.f("ix_opportunity_risk_flags_opportunity_id"),
        "opportunity_risk_flags",
        ["opportunity_id"],
        unique=False,
        if_not_exists=True,
    )
    op.alter_column(
        "personality_dimensions",
        "risk_appetite",
        existing_type=sa.NUMERIC(precision=5, scale=2),
        nullable=False,
        existing_server_default=sa.text("'0'::numeric"),
    )
    op.alter_column(
        "personality_dimensions",
        "domain_expertise",
        existing_type=sa.NUMERIC(precision=5, scale=2),
        nullable=False,
        existing_server_default=sa.text("'0'::numeric"),
    )
    op.alter_column(
        "personality_dimensions",
        "investment_capacity",
        existing_type=sa.NUMERIC(precision=5, scale=2),
        nullable=False,
        existing_server_default=sa.text("'0'::numeric"),
    )
    op.alter_column(
        "personality_dimensions",
        "time_commitment",
        existing_type=sa.NUMERIC(precision=5, scale=2),
        nullable=False,
        existing_server_default=sa.text("'0'::numeric"),
    )
    op.alter_column(
        "personality_dimensions",
        "network_strength",
        existing_type=sa.NUMERIC(precision=5, scale=2),
        nullable=False,
        existing_server_default=sa.text("'0'::numeric"),
    )
    op.alter_column(
        "personality_dimensions",
        "creativity_score",
        existing_type=sa.NUMERIC(precision=5, scale=2),
        nullable=False,
        existing_server_default=sa.text("'0'::numeric"),
    )
    op.alter_column(
        "personality_dimensions",
        "leadership_score",
        existing_type=sa.NUMERIC(precision=5, scale=2),
        nullable=False,
        existing_server_default=sa.text("'0'::numeric"),
    )
    op.alter_column(
        "personality_dimensions",
        "collaboration_score",
        existing_type=sa.NUMERIC(precision=5, scale=2),
        nullable=False,
        existing_server_default=sa.text("'0'::numeric"),
    )
    op.drop_index(op.f("idx_pd_user"), if_exists=True, table_name="personality_dimensions")
    op.drop_constraint(
        op.f("uq_personality_dim_user_vault"), "personality_dimensions", type_="unique"
    )
    op.create_index(
        op.f("ix_personality_dimensions_user_id"),
        "personality_dimensions",
        ["user_id"],
        unique=False,
        if_not_exists=True,
    )
    op.alter_column(
        "platform_configs",
        "is_active",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("true"),
    )
    op.alter_column(
        "platform_configs",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "platform_configs",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(op.f("idx_platform_configs_key"), if_exists=True, table_name="platform_configs")
    op.drop_index(
        op.f("idx_platform_configs_section"), if_exists=True, table_name="platform_configs"
    )
    op.drop_index(
        op.f("uq_platform_configs_section_key"), if_exists=True, table_name="platform_configs"
    )
    op.create_index(
        op.f("ix_platform_configs_key"),
        "platform_configs",
        ["key"],
        unique=False,
        if_not_exists=True,
    )
    op.create_index(
        op.f("ix_platform_configs_section"),
        "platform_configs",
        ["section"],
        unique=False,
        if_not_exists=True,
    )
    op.drop_table_comment(
        "platform_configs",
        existing_comment="Command Control Centre configuration store",
        schema=None,
    )
    op.drop_index(
        op.f("idx_pms_opportunity_score"), if_exists=True, table_name="profile_match_scores"
    )
    op.drop_index(op.f("idx_pms_user"), if_exists=True, table_name="profile_match_scores")
    op.drop_constraint(op.f("uq_profile_match_score"), "profile_match_scores", type_="unique")
    op.create_index(
        op.f("ix_profile_match_scores_opportunity_id"),
        "profile_match_scores",
        ["opportunity_id"],
        unique=False,
        if_not_exists=True,
    )
    op.create_index(
        op.f("ix_profile_match_scores_user_id"),
        "profile_match_scores",
        ["user_id"],
        unique=False,
        if_not_exists=True,
    )
    op.alter_column(
        "properties",
        "raised_amount",
        existing_type=sa.NUMERIC(precision=15, scale=2),
        nullable=False,
        existing_server_default=sa.text("'0'::numeric"),
    )
    op.alter_column(
        "properties",
        "sold_units",
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "properties",
        "investor_count",
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "properties",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "properties",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(
        op.f("idx_properties_active"),
        table_name="properties",
        postgresql_where="((status)::text <> ALL ((ARRAY['archived'::character varying, 'rejected'::character varying])::text[]))",
    )
    op.drop_index(op.f("idx_properties_created_at"), if_exists=True, table_name="properties")
    op.drop_index(
        op.f("idx_properties_locality_trgm"),
        table_name="properties",
        postgresql_ops={"locality": "gin_trgm_ops"},
        postgresql_using="gin",
    )
    op.drop_index(op.f("idx_properties_status_created"), if_exists=True, table_name="properties")
    op.drop_index(
        op.f("idx_properties_title_trgm"),
        table_name="properties",
        postgresql_ops={"title": "gin_trgm_ops"},
        postgresql_using="gin",
    )
    op.drop_constraint(op.f("properties_builder_id_fkey"), "properties", type_="foreignkey")
    op.create_foreign_key(None, "properties", "builders", ["builder_id"], ["id"])
    op.drop_column("properties", "rera_id")
    op.alter_column(
        "property_referral_codes",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(op.f("ix_prop_ref_code"), if_exists=True, table_name="property_referral_codes")
    op.drop_index(op.f("ix_prop_ref_user"), if_exists=True, table_name="property_referral_codes")
    op.create_index(
        op.f("ix_property_referral_codes_user_id"),
        "property_referral_codes",
        ["user_id"],
        unique=False,
        if_not_exists=True,
    )
    op.alter_column(
        "referrals",
        "reward_amount",
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "referrals",
        "reward_claimed",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "referrals",
        "referral_type",
        existing_type=sa.VARCHAR(length=20),
        nullable=False,
        existing_server_default=sa.text("'platform'::character varying"),
    )
    op.alter_column(
        "referrals",
        "first_investment_rewarded",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "referrals",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(op.f("idx_referrals_code_used"), if_exists=True, table_name="referrals")
    op.drop_table_comment(
        "role_groups",
        existing_comment="Logical role groups for bulk messaging and access control",
        schema=None,
    )
    op.alter_column(
        "site_content",
        "content_type",
        existing_type=sa.VARCHAR(length=20),
        nullable=False,
        existing_server_default=sa.text("'text'::character varying"),
    )
    op.alter_column(
        "site_content",
        "is_active",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("true"),
    )
    op.alter_column(
        "site_content",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "site_content",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "transactions",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(op.f("idx_transactions_type"), if_exists=True, table_name="transactions")
    op.drop_index(op.f("idx_txn_type_created"), if_exists=True, table_name="transactions")
    op.drop_constraint(op.f("transactions_user_id_fkey"), "transactions", type_="foreignkey")
    op.drop_constraint(op.f("transactions_investment_id_fkey"), "transactions", type_="foreignkey")
    op.create_foreign_key(None, "transactions", "users", ["user_id"], ["id"])
    op.create_foreign_key(None, "transactions", "investments", ["investment_id"], ["id"])
    op.alter_column(
        "user_activities",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(op.f("ix_user_activities_type"), if_exists=True, table_name="user_activities")
    op.create_index(
        op.f("ix_user_activities_activity_type"),
        "user_activities",
        ["activity_type"],
        unique=False,
        if_not_exists=True,
    )
    op.drop_index(op.f("idx_user_points_action"), if_exists=True, table_name="user_points")
    op.drop_index(op.f("idx_user_points_user_id"), if_exists=True, table_name="user_points")
    op.create_index(
        op.f("ix_user_points_action"), "user_points", ["action"], unique=False, if_not_exists=True
    )
    op.create_index(
        op.f("ix_user_points_user_id"), "user_points", ["user_id"], unique=False, if_not_exists=True
    )
    op.drop_table_comment(
        "user_points",
        existing_comment="Gamification: tracks points earned by users for contributions",
        schema=None,
    )
    op.drop_index(op.f("idx_upa_user_vault"), if_exists=True, table_name="user_profile_answers")
    op.drop_constraint(op.f("uq_user_profile_answer"), "user_profile_answers", type_="unique")
    op.create_index(
        op.f("ix_user_profile_answers_user_id"),
        "user_profile_answers",
        ["user_id"],
        unique=False,
        if_not_exists=True,
    )
    op.alter_column(
        "users",
        "avatar_s3_key",
        existing_type=sa.TEXT(),
        comment=None,
        existing_comment="S3 object key for the user's profile photo, e.g. avatars/{user_id}/{uuid}.jpg",
        existing_nullable=True,
    )
    op.alter_column(
        "users",
        "wealth_pass_active",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "users",
        "is_active",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("true"),
    )
    op.alter_column(
        "users",
        "interests",
        existing_type=postgresql.ARRAY(sa.TEXT()),
        type_=postgresql.ARRAY(sa.String()),
        existing_nullable=True,
    )
    op.alter_column(
        "users",
        "preferred_cities",
        existing_type=postgresql.ARRAY(sa.TEXT()),
        type_=postgresql.ARRAY(sa.String()),
        existing_nullable=True,
    )
    op.alter_column(
        "users",
        "subscription_topics",
        existing_type=postgresql.ARRAY(sa.TEXT()),
        type_=postgresql.ARRAY(sa.String()),
        existing_nullable=True,
    )
    op.alter_column(
        "users",
        "skills",
        existing_type=postgresql.ARRAY(sa.TEXT()),
        type_=postgresql.ARRAY(sa.String()),
        existing_nullable=True,
    )
    op.alter_column(
        "users",
        "contribution_interests",
        existing_type=postgresql.ARRAY(sa.TEXT()),
        type_=postgresql.ARRAY(sa.String()),
        existing_nullable=True,
    )
    op.alter_column(
        "users",
        "email_verified",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "users",
        "phone_verified",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "users",
        "profile_completion_pct",
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "users",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "users",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(
        op.f("idx_users_builder_approved"),
        table_name="users",
        postgresql_where="(builder_approved = true)",
    )
    op.drop_index(op.f("idx_users_city"), if_exists=True, table_name="users")
    op.drop_index(op.f("idx_users_email_verified"), if_exists=True, table_name="users")
    op.drop_index(
        op.f("idx_users_phone_unique"),
        table_name="users",
        postgresql_where="((phone IS NOT NULL) AND ((phone)::text <> ''::text))",
    )
    op.drop_index(op.f("idx_users_phone_verified"), if_exists=True, table_name="users")
    op.drop_index(op.f("idx_users_primary_role"), if_exists=True, table_name="users")
    op.drop_index(op.f("idx_users_primary_role_created"), if_exists=True, table_name="users")
    op.drop_index(op.f("idx_users_profile_completion"), if_exists=True, table_name="users")
    op.drop_index(op.f("idx_users_referral_code"), if_exists=True, table_name="users")
    op.drop_index(op.f("idx_users_role"), if_exists=True, table_name="users")
    op.drop_index(
        op.f("idx_users_roles"), if_exists=True, table_name="users", postgresql_using="gin"
    )
    op.drop_index(op.f("ix_users_builder_approved_by"), if_exists=True, table_name="users")
    op.drop_index(op.f("ix_users_referred_by"), if_exists=True, table_name="users")
    op.create_foreign_key(None, "users", "users", ["referred_by"], ["id"])
    op.drop_constraint(op.f("uq_vault_explorer_user_vault"), "vault_explorers", type_="unique")
    op.drop_index(op.f("idx_vff_vault_role"), if_exists=True, table_name="vault_feature_flags")
    op.drop_constraint(
        op.f("vault_feature_flags_vault_type_role_feature_key_key"),
        "vault_feature_flags",
        type_="unique",
    )
    op.create_table_comment(
        "vault_feature_flags",
        "Per vault × per role feature toggles managed via Control Centre",
        existing_comment=None,
        schema=None,
    )
    op.drop_index(
        op.f("idx_vpq_vault_active"), if_exists=True, table_name="vault_profile_questions"
    )
    op.create_index(
        op.f("ix_vault_profile_questions_vault_type"),
        "vault_profile_questions",
        ["vault_type"],
        unique=False,
        if_not_exists=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_vault_profile_questions_vault_type"), table_name="vault_profile_questions"
    )
    op.create_index(
        op.f("idx_vpq_vault_active"),
        "vault_profile_questions",
        ["vault_type", "is_active", "sort_order"],
        unique=False,
        if_not_exists=True,
    )
    op.drop_table_comment(
        "vault_feature_flags",
        existing_comment="Per vault × per role feature toggles managed via Control Centre",
        schema=None,
    )
    op.create_unique_constraint(
        op.f("vault_feature_flags_vault_type_role_feature_key_key"),
        "vault_feature_flags",
        ["vault_type", "role", "feature_key"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_index(
        op.f("idx_vff_vault_role"),
        "vault_feature_flags",
        ["vault_type", "role"],
        unique=False,
        if_not_exists=True,
    )
    op.create_unique_constraint(
        op.f("uq_vault_explorer_user_vault"),
        "vault_explorers",
        ["user_id", "vault_type"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_constraint(None, "users", type_="foreignkey")  # type: ignore[bad-argument-type]
    op.create_index(
        op.f("ix_users_referred_by"), "users", ["referred_by"], unique=False, if_not_exists=True
    )
    op.create_index(
        op.f("ix_users_builder_approved_by"),
        "users",
        ["builder_approved_by"],
        unique=False,
        if_not_exists=True,
    )
    op.create_index(
        op.f("idx_users_roles"),
        "users",
        ["roles"],
        unique=False,
        postgresql_using="gin",
        if_not_exists=True,
    )
    op.create_index(op.f("idx_users_role"), "users", ["role"], unique=False, if_not_exists=True)
    op.create_index(
        op.f("idx_users_referral_code"),
        "users",
        ["referral_code"],
        unique=False,
        if_not_exists=True,
    )
    op.create_index(
        op.f("idx_users_profile_completion"),
        "users",
        ["profile_completion_pct"],
        unique=False,
        if_not_exists=True,
    )
    op.create_index(
        op.f("idx_users_primary_role_created"),
        "users",
        ["primary_role", "created_at"],
        unique=False,
        if_not_exists=True,
    )
    op.create_index(
        op.f("idx_users_primary_role"), "users", ["primary_role"], unique=False, if_not_exists=True
    )
    op.create_index(
        op.f("idx_users_phone_verified"),
        "users",
        ["phone_verified"],
        unique=False,
        if_not_exists=True,
    )
    op.create_index(
        op.f("idx_users_phone_unique"),
        "users",
        ["phone"],
        unique=True,
        postgresql_where="((phone IS NOT NULL) AND ((phone)::text <> ''::text))",
        if_not_exists=True,
    )
    op.create_index(
        op.f("idx_users_email_verified"),
        "users",
        ["email_verified"],
        unique=False,
        if_not_exists=True,
    )
    op.create_index(op.f("idx_users_city"), "users", ["city"], unique=False, if_not_exists=True)
    op.create_index(
        op.f("idx_users_builder_approved"),
        "users",
        ["builder_approved"],
        unique=False,
        postgresql_where="(builder_approved = true)",
        if_not_exists=True,
    )
    op.alter_column(
        "users",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "users",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "users",
        "profile_completion_pct",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "users",
        "phone_verified",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "users",
        "email_verified",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "users",
        "contribution_interests",
        existing_type=postgresql.ARRAY(sa.String()),
        type_=postgresql.ARRAY(sa.TEXT()),
        existing_nullable=True,
    )
    op.alter_column(
        "users",
        "skills",
        existing_type=postgresql.ARRAY(sa.String()),
        type_=postgresql.ARRAY(sa.TEXT()),
        existing_nullable=True,
    )
    op.alter_column(
        "users",
        "subscription_topics",
        existing_type=postgresql.ARRAY(sa.String()),
        type_=postgresql.ARRAY(sa.TEXT()),
        existing_nullable=True,
    )
    op.alter_column(
        "users",
        "preferred_cities",
        existing_type=postgresql.ARRAY(sa.String()),
        type_=postgresql.ARRAY(sa.TEXT()),
        existing_nullable=True,
    )
    op.alter_column(
        "users",
        "interests",
        existing_type=postgresql.ARRAY(sa.String()),
        type_=postgresql.ARRAY(sa.TEXT()),
        existing_nullable=True,
    )
    op.alter_column(
        "users",
        "is_active",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("true"),
    )
    op.alter_column(
        "users",
        "wealth_pass_active",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "users",
        "avatar_s3_key",
        existing_type=sa.TEXT(),
        comment="S3 object key for the user's profile photo, e.g. avatars/{user_id}/{uuid}.jpg",
        existing_nullable=True,
    )
    op.drop_index(
        op.f("ix_user_profile_answers_user_id"), if_exists=True, table_name="user_profile_answers"
    )
    op.create_unique_constraint(
        op.f("uq_user_profile_answer"),
        "user_profile_answers",
        ["user_id", "question_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_index(
        op.f("idx_upa_user_vault"),
        "user_profile_answers",
        ["user_id", "vault_type"],
        unique=False,
        if_not_exists=True,
    )
    op.create_table_comment(
        "user_points",
        "Gamification: tracks points earned by users for contributions",
        existing_comment=None,
        schema=None,
    )
    op.drop_index(op.f("ix_user_points_user_id"), if_exists=True, table_name="user_points")
    op.drop_index(op.f("ix_user_points_action"), if_exists=True, table_name="user_points")
    op.create_index(
        op.f("idx_user_points_user_id"),
        "user_points",
        ["user_id"],
        unique=False,
        if_not_exists=True,
    )
    op.create_index(
        op.f("idx_user_points_action"), "user_points", ["action"], unique=False, if_not_exists=True
    )
    op.drop_index(
        op.f("ix_user_activities_activity_type"), if_exists=True, table_name="user_activities"
    )
    op.create_index(
        op.f("ix_user_activities_type"),
        "user_activities",
        ["activity_type"],
        unique=False,
        if_not_exists=True,
    )
    op.alter_column(
        "user_activities",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.drop_constraint(None, "transactions", type_="foreignkey")  # type: ignore[bad-argument-type]
    op.drop_constraint(None, "transactions", type_="foreignkey")  # type: ignore[bad-argument-type]
    op.create_foreign_key(
        op.f("transactions_investment_id_fkey"),
        "transactions",
        "investments",
        ["investment_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        op.f("transactions_user_id_fkey"),
        "transactions",
        "users",
        ["user_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_index(
        op.f("idx_txn_type_created"),
        "transactions",
        ["type", "created_at"],
        unique=False,
        if_not_exists=True,
    )
    op.create_index(
        op.f("idx_transactions_type"), "transactions", ["type"], unique=False, if_not_exists=True
    )
    op.alter_column(
        "transactions",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "site_content",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "site_content",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "site_content",
        "is_active",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("true"),
    )
    op.alter_column(
        "site_content",
        "content_type",
        existing_type=sa.VARCHAR(length=20),
        nullable=True,
        existing_server_default=sa.text("'text'::character varying"),
    )
    op.create_table_comment(
        "role_groups",
        "Logical role groups for bulk messaging and access control",
        existing_comment=None,
        schema=None,
    )
    op.create_index(
        op.f("idx_referrals_code_used"),
        "referrals",
        ["code_used"],
        unique=False,
        if_not_exists=True,
    )
    op.alter_column(
        "referrals",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "referrals",
        "first_investment_rewarded",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "referrals",
        "referral_type",
        existing_type=sa.VARCHAR(length=20),
        nullable=True,
        existing_server_default=sa.text("'platform'::character varying"),
    )
    op.alter_column(
        "referrals",
        "reward_claimed",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "referrals",
        "reward_amount",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_server_default=sa.text("0"),
    )
    op.drop_index(
        op.f("ix_property_referral_codes_user_id"),
        if_exists=True,
        table_name="property_referral_codes",
    )
    op.create_index(
        op.f("ix_prop_ref_user"),
        "property_referral_codes",
        ["user_id"],
        unique=False,
        if_not_exists=True,
    )
    op.create_index(
        op.f("ix_prop_ref_code"),
        "property_referral_codes",
        ["code"],
        unique=False,
        if_not_exists=True,
    )
    op.alter_column(
        "property_referral_codes",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.add_column(
        "properties",
        sa.Column("rera_id", sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "properties", type_="foreignkey")  # type: ignore[bad-argument-type]
    op.create_foreign_key(
        op.f("properties_builder_id_fkey"),
        "properties",
        "builders",
        ["builder_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_index(
        op.f("idx_properties_title_trgm"),
        "properties",
        ["title"],
        unique=False,
        postgresql_ops={"title": "gin_trgm_ops"},
        postgresql_using="gin",
        if_not_exists=True,
    )
    op.create_index(
        op.f("idx_properties_status_created"),
        "properties",
        ["status", sa.literal_column("created_at DESC")],
        unique=False,
        if_not_exists=True,
    )
    op.create_index(
        op.f("idx_properties_locality_trgm"),
        "properties",
        ["locality"],
        unique=False,
        postgresql_ops={"locality": "gin_trgm_ops"},
        postgresql_using="gin",
        if_not_exists=True,
    )
    op.create_index(
        op.f("idx_properties_created_at"),
        "properties",
        [sa.literal_column("created_at DESC")],
        unique=False,
        if_not_exists=True,
    )
    op.create_index(
        op.f("idx_properties_active"),
        "properties",
        ["city", "asset_type"],
        unique=False,
        postgresql_where="((status)::text <> ALL ((ARRAY['archived'::character varying, 'rejected'::character varying])::text[]))",
        if_not_exists=True,
    )
    op.alter_column(
        "properties",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "properties",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "properties",
        "investor_count",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "properties",
        "sold_units",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "properties",
        "raised_amount",
        existing_type=sa.NUMERIC(precision=15, scale=2),
        nullable=True,
        existing_server_default=sa.text("'0'::numeric"),
    )
    op.drop_index(
        op.f("ix_profile_match_scores_user_id"), if_exists=True, table_name="profile_match_scores"
    )
    op.drop_index(
        op.f("ix_profile_match_scores_opportunity_id"),
        if_exists=True,
        table_name="profile_match_scores",
    )
    op.create_unique_constraint(
        op.f("uq_profile_match_score"),
        "profile_match_scores",
        ["user_id", "opportunity_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_index(
        op.f("idx_pms_user"), "profile_match_scores", ["user_id"], unique=False, if_not_exists=True
    )
    op.create_index(
        op.f("idx_pms_opportunity_score"),
        "profile_match_scores",
        ["opportunity_id", sa.literal_column("overall_score DESC")],
        unique=False,
        if_not_exists=True,
    )
    op.create_table_comment(
        "platform_configs",
        "Command Control Centre configuration store",
        existing_comment=None,
        schema=None,
    )
    op.drop_index(
        op.f("ix_platform_configs_section"), if_exists=True, table_name="platform_configs"
    )
    op.drop_index(op.f("ix_platform_configs_key"), if_exists=True, table_name="platform_configs")
    op.create_index(
        op.f("uq_platform_configs_section_key"),
        "platform_configs",
        ["section", "key"],
        unique=True,
        if_not_exists=True,
    )
    op.create_index(
        op.f("idx_platform_configs_section"),
        "platform_configs",
        ["section"],
        unique=False,
        if_not_exists=True,
    )
    op.create_index(
        op.f("idx_platform_configs_key"),
        "platform_configs",
        ["key"],
        unique=False,
        if_not_exists=True,
    )
    op.alter_column(
        "platform_configs",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "platform_configs",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "platform_configs",
        "is_active",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("true"),
    )
    op.drop_index(
        op.f("ix_personality_dimensions_user_id"),
        if_exists=True,
        table_name="personality_dimensions",
    )
    op.create_unique_constraint(
        op.f("uq_personality_dim_user_vault"),
        "personality_dimensions",
        ["user_id", "vault_type"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_index(
        op.f("idx_pd_user"), "personality_dimensions", ["user_id"], unique=False, if_not_exists=True
    )
    op.alter_column(
        "personality_dimensions",
        "collaboration_score",
        existing_type=sa.NUMERIC(precision=5, scale=2),
        nullable=True,
        existing_server_default=sa.text("'0'::numeric"),
    )
    op.alter_column(
        "personality_dimensions",
        "leadership_score",
        existing_type=sa.NUMERIC(precision=5, scale=2),
        nullable=True,
        existing_server_default=sa.text("'0'::numeric"),
    )
    op.alter_column(
        "personality_dimensions",
        "creativity_score",
        existing_type=sa.NUMERIC(precision=5, scale=2),
        nullable=True,
        existing_server_default=sa.text("'0'::numeric"),
    )
    op.alter_column(
        "personality_dimensions",
        "network_strength",
        existing_type=sa.NUMERIC(precision=5, scale=2),
        nullable=True,
        existing_server_default=sa.text("'0'::numeric"),
    )
    op.alter_column(
        "personality_dimensions",
        "time_commitment",
        existing_type=sa.NUMERIC(precision=5, scale=2),
        nullable=True,
        existing_server_default=sa.text("'0'::numeric"),
    )
    op.alter_column(
        "personality_dimensions",
        "investment_capacity",
        existing_type=sa.NUMERIC(precision=5, scale=2),
        nullable=True,
        existing_server_default=sa.text("'0'::numeric"),
    )
    op.alter_column(
        "personality_dimensions",
        "domain_expertise",
        existing_type=sa.NUMERIC(precision=5, scale=2),
        nullable=True,
        existing_server_default=sa.text("'0'::numeric"),
    )
    op.alter_column(
        "personality_dimensions",
        "risk_appetite",
        existing_type=sa.NUMERIC(precision=5, scale=2),
        nullable=True,
        existing_server_default=sa.text("'0'::numeric"),
    )
    op.drop_index(
        op.f("ix_opportunity_risk_flags_opportunity_id"), table_name="opportunity_risk_flags"
    )
    op.create_index(
        op.f("ix_orf_opportunity"),
        "opportunity_risk_flags",
        ["opportunity_id"],
        unique=False,
        if_not_exists=True,
    )
    op.drop_index(
        op.f("ix_opportunity_media_opportunity_id"), if_exists=True, table_name="opportunity_media"
    )
    op.create_index(
        op.f("ix_om_assessment"),
        "opportunity_media",
        ["opportunity_id", "assessment_category_code", "assessment_subcategory_code"],
        unique=False,
        if_not_exists=True,
    )
    op.create_index(
        op.f("idx_opp_media_type"),
        "opportunity_media",
        ["media_type"],
        unique=False,
        if_not_exists=True,
    )
    op.create_index(
        op.f("idx_opp_media_opportunity_id"),
        "opportunity_media",
        ["opportunity_id"],
        unique=False,
        if_not_exists=True,
    )
    op.create_index(
        op.f("idx_opp_media_opp_id"),
        "opportunity_media",
        ["opportunity_id"],
        unique=False,
        if_not_exists=True,
    )
    op.alter_column(
        "opportunity_media",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "opportunity_media",
        "sort_order",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "opportunity_media",
        "filename",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(length=500),
        existing_nullable=True,
    )
    op.alter_column(
        "opportunity_media",
        "media_type",
        existing_type=sa.String(length=10),
        type_=sa.VARCHAR(length=20),
        existing_nullable=False,
        existing_server_default=sa.text("'image'::character varying"),
    )
    op.drop_index(
        op.f("ix_opportunity_likes_user_id"), if_exists=True, table_name="opportunity_likes"
    )
    op.drop_index(
        op.f("ix_opportunity_likes_opportunity_id"), if_exists=True, table_name="opportunity_likes"
    )
    op.create_index(
        op.f("ix_opp_likes_user_id"),
        "opportunity_likes",
        ["user_id"],
        unique=False,
        if_not_exists=True,
    )
    op.create_index(
        op.f("ix_opp_likes_opportunity_id"),
        "opportunity_likes",
        ["opportunity_id"],
        unique=False,
        if_not_exists=True,
    )
    op.alter_column(
        "opportunity_likes",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.create_table_comment(
        "opportunity_investments",
        "Links investments to specific opportunities for vault-level aggregation",
        existing_comment=None,
        schema=None,
    )
    op.drop_index(
        op.f("ix_opportunity_investments_user_id"),
        if_exists=True,
        table_name="opportunity_investments",
    )
    op.drop_index(
        op.f("ix_opportunity_investments_status"),
        if_exists=True,
        table_name="opportunity_investments",
    )
    op.drop_index(
        op.f("ix_opportunity_investments_opportunity_id"), table_name="opportunity_investments"
    )
    op.create_index(
        op.f("idx_opp_investments_user"),
        "opportunity_investments",
        ["user_id"],
        unique=False,
        if_not_exists=True,
    )
    op.create_index(
        op.f("idx_opp_investments_status"),
        "opportunity_investments",
        ["status"],
        unique=False,
        if_not_exists=True,
    )
    op.create_index(
        op.f("idx_opp_investments_opportunity"),
        "opportunity_investments",
        ["opportunity_id"],
        unique=False,
        if_not_exists=True,
    )
    op.create_index(
        op.f("idx_opp_investments_opp_status"),
        "opportunity_investments",
        ["opportunity_id", "status"],
        unique=False,
        if_not_exists=True,
    )
    op.create_index(
        op.f("idx_opp_inv_status_created"),
        "opportunity_investments",
        ["status", "created_at"],
        unique=False,
        if_not_exists=True,
    )
    op.alter_column(
        "opportunity_investments",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "opportunity_investments",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "opportunity_investments",
        "returns_amount",
        existing_type=sa.NUMERIC(precision=15, scale=2),
        nullable=True,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "opportunity_form_options",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.create_unique_constraint(
        op.f("uq_opportunity_documents_opp_doc_type"),
        "opportunity_documents",
        ["opportunity_id", "doc_type"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_index(
        op.f("ix_opportunity_custom_questions_opportunity_id"),
        table_name="opportunity_custom_questions",
    )
    op.create_index(
        op.f("idx_ocq_opportunity"),
        "opportunity_custom_questions",
        ["opportunity_id", "sort_order"],
        unique=False,
        if_not_exists=True,
    )
    op.drop_index(
        op.f("ix_opportunity_comm_mappings_opportunity_id"), table_name="opportunity_comm_mappings"
    )
    op.create_index(
        op.f("ix_comm_mappings_opportunity_id"),
        "opportunity_comm_mappings",
        ["opportunity_id"],
        unique=False,
        if_not_exists=True,
    )
    op.alter_column(
        "opportunity_comm_mappings",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(
        op.f("ix_opportunity_assessments_status"),
        if_exists=True,
        table_name="opportunity_assessments",
    )
    op.drop_index(
        op.f("ix_opportunity_assessments_opportunity_id"), table_name="opportunity_assessments"
    )
    op.drop_index(
        op.f("ix_opportunity_assessments_category_code"), table_name="opportunity_assessments"
    )
    op.create_index(
        op.f("ix_oa_status"),
        "opportunity_assessments",
        ["status"],
        unique=False,
        if_not_exists=True,
    )
    op.create_index(
        op.f("ix_oa_opportunity"),
        "opportunity_assessments",
        ["opportunity_id"],
        unique=False,
        if_not_exists=True,
    )
    op.create_index(
        op.f("ix_oa_category"),
        "opportunity_assessments",
        ["category_code"],
        unique=False,
        if_not_exists=True,
    )
    op.drop_index(
        op.f("ix_opportunity_application_answers_user_id"),
        table_name="opportunity_application_answers",
    )
    op.create_unique_constraint(
        op.f("uq_opp_application_answer"),
        "opportunity_application_answers",
        ["user_id", "question_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_index(
        op.f("idx_oaa_user_opp"),
        "opportunity_application_answers",
        ["user_id", "opportunity_id"],
        unique=False,
        if_not_exists=True,
    )
    op.create_table_comment(
        "opportunities",
        "Multi-vault investment opportunities (Wealth / Opportunity / Community)",
        existing_comment=None,
        schema=None,
    )
    op.drop_constraint(None, "opportunities", type_="foreignkey")  # type: ignore[bad-argument-type]
    op.create_foreign_key(
        op.f("opportunities_company_id_fkey"),
        "opportunities",
        "companies",
        ["company_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_index(op.f("ix_opportunities_vault_type"), if_exists=True, table_name="opportunities")
    op.drop_index(op.f("ix_opportunities_status"), if_exists=True, table_name="opportunities")
    op.drop_index(op.f("ix_opportunities_slug"), if_exists=True, table_name="opportunities")
    op.drop_index(op.f("ix_opportunities_city"), if_exists=True, table_name="opportunities")
    op.create_unique_constraint(
        op.f("opportunities_slug_key"),
        "opportunities",
        ["slug"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_index(
        op.f("ix_opportunities_investment_mode"),
        "opportunities",
        ["investment_mode"],
        unique=False,
        if_not_exists=True,
    )
    op.create_index(
        op.f("ix_opportunities_approval_id"),
        "opportunities",
        ["approval_id"],
        unique=False,
        if_not_exists=True,
    )
    op.create_index(
        op.f("idx_opportunities_vault_type"),
        "opportunities",
        ["vault_type"],
        unique=False,
        if_not_exists=True,
    )
    op.create_index(
        op.f("idx_opportunities_vault_status"),
        "opportunities",
        ["vault_type", "status"],
        unique=False,
        if_not_exists=True,
    )
    op.create_index(
        op.f("idx_opportunities_status"),
        "opportunities",
        ["status"],
        unique=False,
        if_not_exists=True,
    )
    op.create_index(
        op.f("idx_opportunities_slug"), "opportunities", ["slug"], unique=False, if_not_exists=True
    )
    op.create_index(
        op.f("idx_opportunities_creator"),
        "opportunities",
        ["creator_id"],
        unique=False,
        if_not_exists=True,
    )
    op.create_index(
        op.f("idx_opportunities_company"),
        "opportunities",
        ["company_id"],
        unique=False,
        if_not_exists=True,
    )
    op.create_index(
        op.f("idx_opportunities_community_subtype"),
        "opportunities",
        ["community_subtype"],
        unique=False,
        postgresql_where="(community_subtype IS NOT NULL)",
        if_not_exists=True,
    )
    op.create_index(
        op.f("idx_opportunities_city"), "opportunities", ["city"], unique=False, if_not_exists=True
    )
    op.create_index(
        op.f("idx_opp_vault_status"),
        "opportunities",
        ["vault_type", "status"],
        unique=False,
        if_not_exists=True,
    )
    op.create_index(
        op.f("idx_opp_company"), "opportunities", ["company_id"], unique=False, if_not_exists=True
    )
    op.alter_column(
        "opportunities",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "opportunities",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "opportunities",
        "investor_count",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "opportunities",
        "raised_amount",
        existing_type=sa.NUMERIC(precision=15, scale=2),
        nullable=True,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "opportunities",
        "country",
        existing_type=sa.VARCHAR(length=100),
        nullable=True,
        existing_server_default=sa.text("'India'::character varying"),
    )
    op.create_table_comment(
        "notifications",
        "In-app, email, push notification tracking",
        existing_comment=None,
        schema=None,
    )
    op.drop_index(op.f("ix_notifications_user_id"), if_exists=True, table_name="notifications")
    op.drop_index(op.f("ix_notifications_created_at"), if_exists=True, table_name="notifications")
    op.create_index(
        op.f("idx_notifications_user_id"),
        "notifications",
        ["user_id"],
        unique=False,
        if_not_exists=True,
    )
    op.create_index(
        op.f("idx_notifications_user_created"),
        "notifications",
        ["user_id", sa.literal_column("created_at DESC")],
        unique=False,
        if_not_exists=True,
    )
    op.create_index(
        op.f("idx_notifications_unread"),
        "notifications",
        ["user_id"],
        unique=False,
        postgresql_where="(read_at IS NULL)",
        if_not_exists=True,
    )
    op.create_index(
        op.f("idx_notifications_is_read"),
        "notifications",
        ["is_read"],
        unique=False,
        if_not_exists=True,
    )
    op.alter_column(
        "notifications",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "notifications",
        "is_read",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("false"),
    )
    op.create_index(op.f("idx_loans_status"), "loans", ["status"], unique=False, if_not_exists=True)
    op.create_index(
        op.f("idx_loans_lender_status"),
        "loans",
        ["lender_id", "status"],
        unique=False,
        if_not_exists=True,
    )
    op.create_index(
        op.f("idx_loans_lender"), "loans", ["lender_id", "status"], unique=False, if_not_exists=True
    )
    op.alter_column(
        "loans",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "loans",
        "amount_repaid",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "kyc_documents",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "kyc_documents",
        "verification_status",
        existing_type=sa.VARCHAR(length=20),
        nullable=True,
        existing_server_default=sa.text("'PENDING'::character varying"),
    )
    op.drop_constraint(None, "investments", type_="foreignkey")  # type: ignore[bad-argument-type]
    op.drop_constraint(None, "investments", type_="foreignkey")  # type: ignore[bad-argument-type]
    op.create_foreign_key(
        op.f("investments_user_id_fkey"),
        "investments",
        "users",
        ["user_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        op.f("investments_property_id_fkey"),
        "investments",
        "properties",
        ["property_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_index(
        op.f("idx_investments_user_status"),
        "investments",
        ["user_id", "status"],
        unique=False,
        if_not_exists=True,
    )
    op.create_index(
        op.f("idx_investments_status"), "investments", ["status"], unique=False, if_not_exists=True
    )
    op.create_index(
        op.f("idx_investments_razorpay_order_id"),
        "investments",
        ["razorpay_order_id"],
        unique=False,
        if_not_exists=True,
    )
    op.create_index(
        op.f("idx_inv_status_created"),
        "investments",
        ["status", "created_at"],
        unique=False,
        if_not_exists=True,
    )
    op.alter_column(
        "investments",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "investments",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.create_index(
        op.f("ix_investment_txn_records_user_id"),
        "investment_transaction_records",
        ["user_id"],
        unique=False,
        if_not_exists=True,
    )
    op.create_index(
        op.f("ix_investment_txn_records_opp_inv_id"),
        "investment_transaction_records",
        ["opportunity_investment_id"],
        unique=False,
        if_not_exists=True,
    )
    op.create_index(
        op.f("ix_investment_txn_records_legacy_inv_id"),
        "investment_transaction_records",
        ["legacy_investment_id"],
        unique=False,
        if_not_exists=True,
    )
    op.create_table_comment(
        "indian_pincodes",
        "India Post pincode reference for address auto-fill",
        existing_comment=None,
        schema=None,
    )
    op.alter_column(
        "indian_pincodes",
        "delivery",
        existing_type=sa.VARCHAR(length=10),
        nullable=True,
        existing_server_default=sa.text("'Delivery'::character varying"),
    )
    op.create_table_comment(
        "group_messages", "Messages sent to role groups", existing_comment=None, schema=None
    )
    op.drop_index(op.f("ix_group_messages_group_id"), if_exists=True, table_name="group_messages")
    op.create_index(
        op.f("idx_group_messages_group_id"),
        "group_messages",
        ["group_id"],
        unique=False,
        if_not_exists=True,
    )
    op.drop_index(
        op.f("ix_expressions_of_interest_status"),
        if_exists=True,
        table_name="expressions_of_interest",
    )
    op.create_index(
        op.f("ix_eoi_user_id"),
        "expressions_of_interest",
        ["user_id"],
        unique=False,
        if_not_exists=True,
    )
    op.create_index(
        op.f("ix_eoi_status"),
        "expressions_of_interest",
        ["status"],
        unique=False,
        if_not_exists=True,
    )
    op.create_index(
        op.f("ix_eoi_opportunity_id"),
        "expressions_of_interest",
        ["opportunity_id"],
        unique=False,
        if_not_exists=True,
    )
    op.create_index(
        op.f("idx_eoi_user_id"),
        "expressions_of_interest",
        ["user_id"],
        unique=False,
        if_not_exists=True,
    )
    op.create_index(
        op.f("idx_eoi_status_opid"),
        "expressions_of_interest",
        ["status", "opportunity_id"],
        unique=False,
        if_not_exists=True,
    )
    op.create_index(
        op.f("idx_eoi_status"),
        "expressions_of_interest",
        ["status"],
        unique=False,
        if_not_exists=True,
    )
    op.create_index(
        op.f("idx_eoi_opportunity_status"),
        "expressions_of_interest",
        ["opportunity_id", "status"],
        unique=False,
        if_not_exists=True,
    )
    op.alter_column(
        "expressions_of_interest",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "expressions_of_interest",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "expressions_of_interest",
        "communication_consent",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("true"),
    )
    op.create_index(
        op.f("idx_eoi_stage_history_eoi_status"),
        "eoi_stage_history",
        ["eoi_id", "status"],
        unique=False,
        if_not_exists=True,
    )
    op.create_index(
        op.f("idx_eoi_stage_history_eoi"),
        "eoi_stage_history",
        ["eoi_id"],
        unique=False,
        if_not_exists=True,
    )
    op.drop_index(
        op.f("ix_eoi_question_answers_eoi_id"), if_exists=True, table_name="eoi_question_answers"
    )
    op.create_index(
        op.f("ix_eoi_qa_eoi_id"),
        "eoi_question_answers",
        ["eoi_id"],
        unique=False,
        if_not_exists=True,
    )
    op.alter_column(
        "eoi_question_answers",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.create_index(
        op.f("ix_eoi_form_options_field_active"),
        "eoi_form_options",
        ["field_name", "is_active"],
        unique=False,
        if_not_exists=True,
    )
    op.add_column(
        "companies",
        sa.Column("rera_number", sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    )
    op.create_table_comment(
        "companies",
        "Builder/developer company profiles for opportunity creation",
        existing_comment=None,
        schema=None,
    )
    op.drop_index(op.f("ix_companies_user_id"), if_exists=True, table_name="companies")
    op.create_index(
        op.f("ix_companies_approval_id"),
        "companies",
        ["approval_id"],
        unique=False,
        if_not_exists=True,
    )
    op.create_index(
        op.f("idx_companies_verified"), "companies", ["verified"], unique=False, if_not_exists=True
    )
    op.create_index(
        op.f("idx_companies_user_id"), "companies", ["user_id"], unique=False, if_not_exists=True
    )
    op.create_index(
        op.f("idx_companies_user"), "companies", ["user_id"], unique=False, if_not_exists=True
    )
    op.create_index(
        op.f("idx_companies_name"), "companies", ["company_name"], unique=False, if_not_exists=True
    )
    op.create_index(
        op.f("idx_companies_cin"),
        "companies",
        ["cin"],
        unique=True,
        postgresql_where="(cin IS NOT NULL)",
        if_not_exists=True,
    )
    op.alter_column(
        "companies",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "companies",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "companies",
        "verification_status",
        existing_type=sa.VARCHAR(length=20),
        nullable=True,
        existing_server_default=sa.text("'pending'::character varying"),
    )
    op.alter_column(
        "companies",
        "verified",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "companies",
        "projects_completed",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "companies",
        "country",
        existing_type=sa.VARCHAR(length=100),
        nullable=True,
        existing_server_default=sa.text("'India'::character varying"),
    )
    op.add_column(
        "builders",
        sa.Column("rera_number", sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "builders", type_="foreignkey")  # type: ignore[bad-argument-type]
    op.create_foreign_key(
        op.f("builders_user_id_fkey"), "builders", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.alter_column(
        "builders",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "builders",
        "total_sqft_delivered",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "builders",
        "projects_completed",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "builders",
        "verified",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("false"),
    )
    op.create_index(
        op.f("ix_builder_updates_creator_id"),
        "builder_updates",
        ["creator_id"],
        unique=False,
        if_not_exists=True,
    )
    op.alter_column(
        "builder_questions",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "builder_questions",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "builder_questions",
        "sort_order",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "builder_questions",
        "is_required",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("true"),
    )
    op.drop_table_comment(
        "bank_details", existing_comment="Bank details with encrypted sensitive fields", schema=None
    )
    op.drop_index(op.f("ix_bank_details_user_id"), if_exists=True, table_name="bank_details")
    op.create_index(
        op.f("idx_bank_details_user_id"),
        "bank_details",
        ["user_id"],
        unique=False,
        if_not_exists=True,
    )
    op.create_index(
        op.f("idx_audit_logs_resource"),
        "audit_logs",
        ["resource_type", "resource_id"],
        unique=False,
        if_not_exists=True,
    )
    op.create_index(
        op.f("idx_audit_logs_created_brin"),
        "audit_logs",
        ["created_at"],
        unique=False,
        postgresql_using="brin",
        if_not_exists=True,
    )
    op.create_index(
        op.f("idx_audit_logs_created_at"),
        "audit_logs",
        [sa.literal_column("created_at DESC")],
        unique=False,
        if_not_exists=True,
    )
    op.create_index(
        op.f("idx_audit_logs_actor"),
        "audit_logs",
        ["actor_id"],
        unique=False,
        postgresql_where="(actor_id IS NOT NULL)",
        if_not_exists=True,
    )
    op.alter_column(
        "audit_logs",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.create_table_comment(
        "approval_requests",
        "Generic approval workflow for all platform actions",
        existing_comment=None,
        schema=None,
    )
    op.drop_index(
        op.f("ix_approval_requests_status"), if_exists=True, table_name="approval_requests"
    )
    op.drop_index(
        op.f("ix_approval_requests_reviewer_id"), if_exists=True, table_name="approval_requests"
    )
    op.drop_index(
        op.f("ix_approval_requests_created_at"), if_exists=True, table_name="approval_requests"
    )
    op.drop_index(
        op.f("ix_approval_requests_category"), if_exists=True, table_name="approval_requests"
    )
    op.create_index(
        op.f("idx_approval_requests_status"),
        "approval_requests",
        ["status"],
        unique=False,
        if_not_exists=True,
    )
    op.create_index(
        op.f("idx_approval_requests_reviewer"),
        "approval_requests",
        ["reviewer_id"],
        unique=False,
        if_not_exists=True,
    )
    op.create_index(
        op.f("idx_approval_requests_requester"),
        "approval_requests",
        ["requester_id"],
        unique=False,
        if_not_exists=True,
    )
    op.create_index(
        op.f("idx_approval_requests_created_at"),
        "approval_requests",
        ["created_at"],
        unique=False,
        if_not_exists=True,
    )
    op.create_index(
        op.f("idx_approval_requests_category_status"),
        "approval_requests",
        ["category", "status"],
        unique=False,
        if_not_exists=True,
    )
    op.create_index(
        op.f("idx_approval_requests_category"),
        "approval_requests",
        ["category"],
        unique=False,
        if_not_exists=True,
    )
    op.alter_column(
        "approval_requests",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "approval_requests",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "approval_requests",
        "auto_approve",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("false"),
    )
    op.create_unique_constraint(
        op.f("uq_app_video_page_section"),
        "app_videos",
        ["page", "section_tag"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_index(
        op.f("ix_app_videos_uploaded_by"),
        "app_videos",
        ["uploaded_by"],
        unique=False,
        if_not_exists=True,
    )
    op.create_index(
        op.f("idx_app_videos_page_section"),
        "app_videos",
        ["page", "section_tag"],
        unique=False,
        if_not_exists=True,
    )
    op.create_index(
        op.f("idx_app_videos_page"), "app_videos", ["page"], unique=False, if_not_exists=True
    )
    op.create_index(
        op.f("idx_app_videos_active"),
        "app_videos",
        ["is_active"],
        unique=False,
        postgresql_where="(is_active = true)",
        if_not_exists=True,
    )
    op.alter_column(
        "app_videos",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "app_videos",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "app_videos",
        "sort_order",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "app_videos",
        "is_active",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("true"),
    )
    op.create_unique_constraint(
        op.f("uq_app_image_page_section"),
        "app_images",
        ["page", "section_tag"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_index(
        op.f("idx_app_images_page_section"),
        "app_images",
        ["page", "section_tag"],
        unique=False,
        if_not_exists=True,
    )
    op.create_index(
        op.f("idx_app_images_page"), "app_images", ["page"], unique=False, if_not_exists=True
    )
    op.create_index(
        op.f("idx_app_images_active"),
        "app_images",
        ["is_active"],
        unique=False,
        postgresql_where="(is_active = true)",
        if_not_exists=True,
    )
    op.alter_column(
        "app_images",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "app_images",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "app_images",
        "sort_order",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "app_images",
        "is_active",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("true"),
    )
    op.drop_table_comment(
        "admin_invites",
        existing_comment="Invite tokens for admin/super_admin role onboarding",
        schema=None,
    )
    op.create_index(
        op.f("idx_admin_invites_token"),
        "admin_invites",
        ["token"],
        unique=False,
        if_not_exists=True,
    )
    op.create_index(
        op.f("idx_admin_invites_email"),
        "admin_invites",
        ["email"],
        unique=False,
        if_not_exists=True,
    )
    op.drop_index(op.f("ix_consent_logs_target_id"), if_exists=True, table_name="consent_logs")
    op.drop_index(op.f("ix_consent_logs_consent_type"), if_exists=True, table_name="consent_logs")
    op.drop_table("consent_logs")
    # ### end Alembic commands ###
