#!/usr/bin/env bash
# ── 01-deploy-azure-infra.sh ──────────────────────────────────────────────────
# Deploys all WealthSpot Azure infrastructure using Bicep.
# Run from the repository root after: az login && az account set --subscription <id>
#
# Usage:
#   chmod +x deployment/scripts/01-deploy-azure-infra.sh
#   ./deployment/scripts/01-deploy-azure-infra.sh
#
# Prerequisites:
#   - Azure CLI >= 2.60  (az --version)
#   - Resource group already created:
#       az group create --name rg-wealthspot-prod --location centralindia
#   - main.parameters.bicepparam updated with your r2EndpointUrl

set -euo pipefail

# ── Configuration ──────────────────────────────────────────────────────────────
RESOURCE_GROUP="${RESOURCE_GROUP:-rg-wealthspot-prod}"
DEPLOYMENT_NAME="wealthspot-infra-$(date +%Y%m%d-%H%M%S)"
BICEP_FILE="$(dirname "$0")/../azure/main.bicep"
PARAMS_FILE="$(dirname "$0")/../azure/main.parameters.bicepparam"

# ── Colour helpers ─────────────────────────────────────────────────────────────
GREEN='\033[0;32m'; YELLOW='\033[1;33m'; RED='\033[0;31m'; NC='\033[0m'
info()    { echo -e "${YELLOW}▶ $*${NC}"; }
success() { echo -e "${GREEN}✔ $*${NC}"; }
error()   { echo -e "${RED}✖ $*${NC}" >&2; exit 1; }

# ── Preflight checks ──────────────────────────────────────────────────────────
info "Checking prerequisites..."
command -v az >/dev/null 2>&1 || error "Azure CLI not found. Install from https://aka.ms/install-azure-cli"
az account show >/dev/null 2>&1 || error "Not logged in. Run: az login"
[[ -f "$PARAMS_FILE" ]] || error "Parameters file not found: $PARAMS_FILE"

SUBSCRIPTION=$(az account show --query id -o tsv)
info "Active subscription: $SUBSCRIPTION"
info "Target resource group: $RESOURCE_GROUP"

# Verify resource group exists
az group show --name "$RESOURCE_GROUP" >/dev/null 2>&1 || \
  error "Resource group '$RESOURCE_GROUP' not found. Create it first:\n  az group create --name $RESOURCE_GROUP --location centralindia"

# ── Validate template before deploying ────────────────────────────────────────
info "Validating Bicep template..."
az deployment group validate \
  --resource-group "$RESOURCE_GROUP" \
  --template-file "$BICEP_FILE" \
  --parameters "$PARAMS_FILE" \
  --output none \
  && success "Template validation passed."

# ── Deploy ────────────────────────────────────────────────────────────────────
info "Deploying infrastructure (this takes 3–6 minutes)..."
OUTPUTS=$(az deployment group create \
  --resource-group "$RESOURCE_GROUP" \
  --name "$DEPLOYMENT_NAME" \
  --template-file "$BICEP_FILE" \
  --parameters "$PARAMS_FILE" \
  --output json)

# ── Extract outputs ────────────────────────────────────────────────────────────
get_output() { echo "$OUTPUTS" | python3 -c "import sys,json; d=json.load(sys.stdin); print(d['properties']['outputs']['$1']['value'])" 2>/dev/null || echo "N/A"; }

ACR_LOGIN_SERVER=$(get_output "acrLoginServer")
ACR_NAME=$(get_output "acrName")
KV_URI=$(get_output "kvUri")
KV_NAME=$(get_output "kvName")
STORAGE_ACCOUNT=$(get_output "storageAccount")
BLOB_ENDPOINT=$(get_output "blobEndpoint")
CONTAINER_APP_FQDN=$(get_output "containerAppFqdn")
CONTAINER_APP_NAME=$(get_output "containerAppName")
IDENTITY_CLIENT_ID=$(get_output "identityClientId")
IDENTITY_PRINCIPAL_ID=$(get_output "identityPrincipalId")

# ── Print summary table ────────────────────────────────────────────────────────
echo ""
success "Infrastructure deployed successfully!"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
printf "%-30s %s\n" "Resource" "Value"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
printf "%-30s %s\n" "ACR Login Server"     "$ACR_LOGIN_SERVER"
printf "%-30s %s\n" "ACR Name"             "$ACR_NAME"
printf "%-30s %s\n" "Key Vault URI"        "$KV_URI"
printf "%-30s %s\n" "Key Vault Name"       "$KV_NAME"
printf "%-30s %s\n" "KYC Storage Account"  "$STORAGE_ACCOUNT"
printf "%-30s %s\n" "KYC Blob Endpoint"    "$BLOB_ENDPOINT"
printf "%-30s %s\n" "Container App FQDN"   "$CONTAINER_APP_FQDN"
printf "%-30s %s\n" "Container App Name"   "$CONTAINER_APP_NAME"
printf "%-30s %s\n" "Identity Client ID"   "$IDENTITY_CLIENT_ID"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# ── Save outputs to a local file for use by other scripts ─────────────────────
OUTPUTS_FILE="$(dirname "$0")/../../.azure/infra-outputs.env"
mkdir -p "$(dirname "$OUTPUTS_FILE")"
cat > "$OUTPUTS_FILE" <<EOF
# Auto-generated by 01-deploy-azure-infra.sh — do not commit
ACR_LOGIN_SERVER=$ACR_LOGIN_SERVER
ACR_NAME=$ACR_NAME
KV_URI=$KV_URI
KV_NAME=$KV_NAME
STORAGE_ACCOUNT=$STORAGE_ACCOUNT
BLOB_ENDPOINT=$BLOB_ENDPOINT
CONTAINER_APP_FQDN=$CONTAINER_APP_FQDN
CONTAINER_APP_NAME=$CONTAINER_APP_NAME
RESOURCE_GROUP=$RESOURCE_GROUP
IDENTITY_CLIENT_ID=$IDENTITY_CLIENT_ID
IDENTITY_PRINCIPAL_ID=$IDENTITY_PRINCIPAL_ID
EOF
success "Outputs saved to .azure/infra-outputs.env"

echo ""
echo -e "${YELLOW}Next step: run ${GREEN}./deployment/scripts/02-configure-secrets.sh${YELLOW} to populate Key Vault secrets.${NC}"
